# Generated by Django 5.2.17 on 2026-09-12 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_mfa_enabled_user_mfa_last_verified_step_and_more'),
        ('organization', '0002_division_supportdivision'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.division'),
        ),
        migrations.AddField(
            model_name='user',
            name='support_division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='organization.supportdivision'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('HEAD_OF_DEPARTMENT', 'Head of Department'), ('HEAD_OF_DIVISION', 'Head of Division'), ('HEAD_OF_SUPPORT_DIVISION', 'Head of Support Division'), ('HEAD_OF_SECTION', 'Head of Section'), ('HEAD_OF_UNIT', 'Head of Unit'), ('HR_ADMIN', 'HR Admin'), ('AUTHORIZING_OFFICER', 'Authorizing Officer'), ('SYSTEM_ADMIN', 'System Admin')], db_index=True, default='EMPLOYEE', max_length=32),
        ),
    ]
