# Generated by Django 5.2.17 on 2026-09-12 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_division_user_support_division_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdditionalRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('HEAD_OF_DEPARTMENT', 'Head of Department'), ('HEAD_OF_DIVISION', 'Head of Division'), ('HEAD_OF_SUPPORT_DIVISION', 'Head of Support Division'), ('HEAD_OF_SECTION', 'Head of Section'), ('HEAD_OF_UNIT', 'Head of Unit'), ('HR_ADMIN', 'HR Admin'), ('AUTHORIZING_OFFICER', 'Authorizing Officer'), ('SYSTEM_ADMIN', 'System Admin')], max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='additional_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'role'), name='uniq_user_additional_role')],
            },
        ),
    ]
