# Generated by Django 5.2.17 on 2026-09-12 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_useradditionalrole'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='station',
            new_name='work_station',
        ),
    ]
