# Generated by Django 5.2.17 on 2026-09-12 15:27, hand-edited: designation
# changes from a free-text CharField to a FK (organization.Designation).
# Existing text values can't be cast to the new integer FK column (unlike a
# straight AlterField), so this drops the old column and adds the new one --
# any previously stored designation text is lost; users get their FK
# assigned afresh via the admin UI.
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_station_user_work_station'),
        ('organization', '0003_designation_rename_station_workstation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='designation',
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                related_name='employees', to='organization.designation',
            ),
        ),
    ]
