# Generated by Django 5.2.17 on 2026-09-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_designation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='sub_vote',
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='user',
            name='vote_code',
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
