# Generated by Django 5.2.17 on 2026-09-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_sub_vote_user_vote_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('HEAD_OF_DEPARTMENT', 'Head of Department'), ('HEAD_OF_DIVISION', 'Head of Division'), ('HEAD_OF_SUPPORT_DIVISION', 'Head of Support Division'), ('HEAD_OF_SECTION', 'Head of Section'), ('HEAD_OF_UNIT', 'Head of Unit'), ('HR_ADMIN', 'HR Admin'), ('AUTHORIZING_OFFICER', 'Authorizing Officer'), ('CAG', 'CAG'), ('SYSTEM_ADMIN', 'System Admin')], db_index=True, default='EMPLOYEE', max_length=32),
        ),
        migrations.AlterField(
            model_name='useradditionalrole',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('HEAD_OF_DEPARTMENT', 'Head of Department'), ('HEAD_OF_DIVISION', 'Head of Division'), ('HEAD_OF_SUPPORT_DIVISION', 'Head of Support Division'), ('HEAD_OF_SECTION', 'Head of Section'), ('HEAD_OF_UNIT', 'Head of Unit'), ('HR_ADMIN', 'HR Admin'), ('AUTHORIZING_OFFICER', 'Authorizing Officer'), ('CAG', 'CAG'), ('SYSTEM_ADMIN', 'System Admin')], max_length=32),
        ),
    ]
