# Generated by Django 5.2.17 on 2026-09-20 12:52

from django.db import migrations, models


def rename_head_of_division_to_dag(apps, schema_editor):
    """HEAD_OF_DIVISION is renamed to DAG -- carry existing rows over so no
    user silently loses their role when the choices change below."""
    User = apps.get_model('accounts', 'User')
    UserAdditionalRole = apps.get_model('accounts', 'UserAdditionalRole')
    User.objects.filter(role='HEAD_OF_DIVISION').update(role='DAG')
    UserAdditionalRole.objects.filter(role='HEAD_OF_DIVISION').update(role='DAG')


def rename_dag_to_head_of_division(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    UserAdditionalRole = apps.get_model('accounts', 'UserAdditionalRole')
    User.objects.filter(role='DAG').update(role='HEAD_OF_DIVISION')
    UserAdditionalRole.objects.filter(role='DAG').update(role='HEAD_OF_DIVISION')


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_role_alter_useradditionalrole_role'),
    ]

    operations = [
        migrations.RunPython(rename_head_of_division_to_dag, rename_dag_to_head_of_division),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('HEAD_OF_DEPARTMENT', 'Head of Department'), ('DAG', 'DAG'), ('HEAD_OF_SUPPORT_DIVISION', 'Head of Support Division'), ('HEAD_OF_SECTION', 'Head of Section'), ('HEAD_OF_UNIT', 'Head of Unit'), ('HR_ADMIN', 'HR Admin'), ('AUTHORIZING_OFFICER', 'Authorizing Officer'), ('CAG', 'CAG'), ('AAG', 'AAG'), ('CHIEF_ACCOUNTANT', 'Chief Accountant'), ('DAHRM', 'DAHRM'), ('ADA', 'ADA'), ('SYSTEM_ADMIN', 'SYSTEM_ADMIN')], db_index=True, default='EMPLOYEE', max_length=32),
        ),
        migrations.AlterField(
            model_name='useradditionalrole',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('HEAD_OF_DEPARTMENT', 'Head of Department'), ('DAG', 'DAG'), ('HEAD_OF_SUPPORT_DIVISION', 'Head of Support Division'), ('HEAD_OF_SECTION', 'Head of Section'), ('HEAD_OF_UNIT', 'Head of Unit'), ('HR_ADMIN', 'HR Admin'), ('AUTHORIZING_OFFICER', 'Authorizing Officer'), ('CAG', 'CAG'), ('AAG', 'AAG'), ('CHIEF_ACCOUNTANT', 'Chief Accountant'), ('DAHRM', 'DAHRM'), ('ADA', 'ADA'), ('SYSTEM_ADMIN', 'SYSTEM_ADMIN')], max_length=32),
        ),
    ]
