# Generated by Django 5.2.17 on 2026-09-20 13:20

from django.db import migrations, models


def reassign_removed_roles_to_employee(apps, schema_editor):
    """HEAD_OF_UNIT and HEAD_OF_SUPPORT_DIVISION are removed from the choices
    below -- downgrade any existing holders to the default EMPLOYEE role
    rather than leaving a role value that's no longer selectable."""
    User = apps.get_model('accounts', 'User')
    UserAdditionalRole = apps.get_model('accounts', 'UserAdditionalRole')
    User.objects.filter(role__in=['HEAD_OF_UNIT', 'HEAD_OF_SUPPORT_DIVISION']).update(role='EMPLOYEE')
    UserAdditionalRole.objects.filter(role__in=['HEAD_OF_UNIT', 'HEAD_OF_SUPPORT_DIVISION']).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_dag_and_leadership_roles'),
    ]

    operations = [
        migrations.RunPython(reassign_removed_roles_to_employee, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='user',
            name='support_division',
        ),
        migrations.RemoveField(
            model_name='user',
            name='unit',
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('HEAD_OF_DEPARTMENT', 'Head of Department'), ('DAG', 'DAG'), ('HEAD_OF_SECTION', 'Head of Section'), ('HR_ADMIN', 'HR Admin'), ('AUTHORIZING_OFFICER', 'Authorizing Officer'), ('CAG', 'CAG'), ('AAG', 'AAG'), ('CHIEF_ACCOUNTANT', 'Chief Accountant'), ('DAHRM', 'DAHRM'), ('ADA', 'ADA'), ('CHIEF_EXTERNAL_AUDITOR', 'Chief External Auditor'), ('SYSTEM_ADMIN', 'SYSTEM_ADMIN')], db_index=True, default='EMPLOYEE', max_length=32),
        ),
        migrations.AlterField(
            model_name='useradditionalrole',
            name='role',
            field=models.CharField(choices=[('EMPLOYEE', 'Employee'), ('HEAD_OF_DEPARTMENT', 'Head of Department'), ('DAG', 'DAG'), ('HEAD_OF_SECTION', 'Head of Section'), ('HR_ADMIN', 'HR Admin'), ('AUTHORIZING_OFFICER', 'Authorizing Officer'), ('CAG', 'CAG'), ('AAG', 'AAG'), ('CHIEF_ACCOUNTANT', 'Chief Accountant'), ('DAHRM', 'DAHRM'), ('ADA', 'ADA'), ('CHIEF_EXTERNAL_AUDITOR', 'Chief External Auditor'), ('SYSTEM_ADMIN', 'SYSTEM_ADMIN')], max_length=32),
        ),
    ]
