# Generated by Django 5.2.17 on 2026-09-21 23:05

from django.db import migrations, models

# Mirrors the behavior that was previously hardcoded across
# apps.leave.permissions/workflow.py and the SYSTEM_ADMIN-only viewsets --
# seeding this exactly means nothing changes on deploy until a SYSTEM_ADMIN
# edits the matrix via the new Roles page.
DEFAULT_ROLE_PERMISSIONS = {
    'EMPLOYEE': ['CREATE_LEAVE_APPLICATION'],
    'HEAD_OF_DEPARTMENT': ['CREATE_LEAVE_APPLICATION', 'RECOMMEND_LEAVE'],
    'DAG': ['CREATE_LEAVE_APPLICATION', 'RECOMMEND_LEAVE'],
    'HEAD_OF_SECTION': ['CREATE_LEAVE_APPLICATION', 'RECOMMEND_LEAVE'],
    'HR_ADMIN': ['CREATE_LEAVE_APPLICATION', 'VERIFY_LEAVE', 'VIEW_REPORTS'],
    'AUTHORIZING_OFFICER': ['CREATE_LEAVE_APPLICATION', 'APPROVE_LEAVE', 'VIEW_REPORTS'],
    'CAG': ['CREATE_LEAVE_APPLICATION', 'CAG_REVIEW_LEAVE'],
    'AAG': ['CREATE_LEAVE_APPLICATION', 'AAG_REVIEW_LEAVE'],
    'CHIEF_ACCOUNTANT': ['CREATE_LEAVE_APPLICATION'],
    'DAHRM': ['CREATE_LEAVE_APPLICATION'],
    'ADA': ['CREATE_LEAVE_APPLICATION'],
    'CHIEF_EXTERNAL_AUDITOR': ['CREATE_LEAVE_APPLICATION'],
    'SYSTEM_ADMIN': [
        'CREATE_LEAVE_APPLICATION', 'RECOMMEND_LEAVE', 'CAG_REVIEW_LEAVE', 'AAG_REVIEW_LEAVE',
        'VERIFY_LEAVE', 'APPROVE_LEAVE', 'MANAGE_USERS', 'MANAGE_LEAVE_TYPES',
        'MANAGE_PERSON_TYPES', 'MANAGE_LEAVE_POLICIES', 'MANAGE_ORGANIZATION', 'VIEW_REPORTS',
    ],
}


def seed_role_permissions(apps, schema_editor):
    RolePermission = apps.get_model('accounts', 'RolePermission')
    RolePermission.objects.bulk_create([
        RolePermission(role=role, permission=permission)
        for role, permissions in DEFAULT_ROLE_PERMISSIONS.items()
        for permission in permissions
    ])


def unseed_role_permissions(apps, schema_editor):
    RolePermission = apps.get_model('accounts', 'RolePermission')
    RolePermission.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_head_of_unit_support_division_add_cea'),
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('EMPLOYEE', 'Employee'), ('HEAD_OF_DEPARTMENT', 'Head of Department'), ('DAG', 'DAG'), ('HEAD_OF_SECTION', 'Head of Section'), ('HR_ADMIN', 'HR Admin'), ('AUTHORIZING_OFFICER', 'Authorizing Officer'), ('CAG', 'CAG'), ('AAG', 'AAG'), ('CHIEF_ACCOUNTANT', 'Chief Accountant'), ('DAHRM', 'DAHRM'), ('ADA', 'ADA'), ('CHIEF_EXTERNAL_AUDITOR', 'Chief External Auditor'), ('SYSTEM_ADMIN', 'SYSTEM_ADMIN')], max_length=32)),
                ('permission', models.CharField(choices=[('CREATE_LEAVE_APPLICATION', 'Create leave applications'), ('RECOMMEND_LEAVE', 'Recommend leave (Section B1 - HOD)'), ('CAG_REVIEW_LEAVE', 'CAG review'), ('AAG_REVIEW_LEAVE', 'AAG review'), ('VERIFY_LEAVE', 'Verify leave (Section B2 - HR)'), ('APPROVE_LEAVE', 'Approve / deny leave (Section C - Authorizing Officer)'), ('MANAGE_USERS', 'Manage users'), ('MANAGE_LEAVE_TYPES', 'Manage leave types'), ('MANAGE_PERSON_TYPES', 'Manage person types'), ('MANAGE_LEAVE_POLICIES', 'Manage leave policies'), ('MANAGE_ORGANIZATION', 'Manage organization structure'), ('VIEW_REPORTS', 'View / export reports')], max_length=64)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('role', 'permission'), name='uniq_role_permission')],
            },
        ),
        migrations.RunPython(seed_role_permissions, unseed_role_permissions),
    ]
