# Generated by Django 5.2.17 on 2026-09-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_grant_recommend_leave_to_cea'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='place_of_domicile',
            field=models.CharField(blank=True, choices=[('ARUSHA', 'Arusha'), ('DAR_ES_SALAAM', 'Dar es Salaam'), ('DODOMA', 'Dodoma'), ('GEITA', 'Geita'), ('IRINGA', 'Iringa'), ('KAGERA', 'Kagera'), ('KATAVI', 'Katavi'), ('KIGOMA', 'Kigoma'), ('KILIMANJARO', 'Kilimanjaro'), ('LINDI', 'Lindi'), ('MANYARA', 'Manyara'), ('MARA', 'Mara'), ('MBEYA', 'Mbeya'), ('MOROGORO', 'Morogoro'), ('MTWARA', 'Mtwara'), ('MWANZA', 'Mwanza'), ('NJOMBE', 'Njombe'), ('PEMBA_NORTH', 'Pemba North'), ('PEMBA_SOUTH', 'Pemba South'), ('PWANI', 'Pwani'), ('RUKWA', 'Rukwa'), ('RUVUMA', 'Ruvuma'), ('SHINYANGA', 'Shinyanga'), ('SIMIYU', 'Simiyu'), ('SINGIDA', 'Singida'), ('SONGWE', 'Songwe'), ('TABORA', 'Tabora'), ('TANGA', 'Tanga'), ('ZANZIBAR_NORTH', 'Zanzibar North'), ('ZANZIBAR_SOUTH', 'Zanzibar South'), ('ZANZIBAR_WEST', 'Zanzibar West')], max_length=32),
        ),
    ]
