# Generated by Django 5.2.17 on 2026-09-22 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_add_place_of_domicile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=32, unique=True)),
                ('display_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['display_name'],
            },
        ),
        migrations.AlterField(
            model_name='rolepermission',
            name='role',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(db_index=True, default='EMPLOYEE', max_length=32),
        ),
        migrations.AlterField(
            model_name='useradditionalrole',
            name='role',
            field=models.CharField(max_length=32),
        ),
    ]
