# Generated by Django 5.2.17 on 2026-09-20 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_head_of_unit_support_division_add_cea'),
        ('organization', '0003_designation_rename_station_workstation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SupportDivision',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
