# Generated by Django 5.2.17 on 2026-09-23 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_remove_head_of_unit_support_division_add_cea'),
    ]

    operations = [
        migrations.AddField(
            model_name='workstation',
            name='division',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_stations', to='organization.division'),
        ),
    ]
