# Generated by Django 6.1.1 on 2026-09-09 13:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('code', models.CharField(max_length=20, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=255)),
                ('is_recurring', models.BooleanField(default=False, help_text='Recurs every year on this month/day (e.g. Christmas).')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date'],
                'constraints': [models.UniqueConstraint(fields=('date', 'name'), name='uniq_holiday_date_name')],
            },
        ),
        migrations.CreateModel(
            name='LeaveApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approved', models.BooleanField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('signature_name', models.CharField(blank=True, max_length=255)),
                ('signature_designation', models.CharField(blank=True, max_length=255)),
                ('signature_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_approvals', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_number', models.CharField(db_index=True, editable=False, max_length=32, unique=True)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING_HOD_REVIEW', 'Pending HOD Review'), ('HOD_RECOMMENDED', 'HOD Recommended'), ('RETURNED_TO_EMPLOYEE', 'Returned to Employee'), ('PENDING_HR_REVIEW', 'Pending HR Review'), ('HR_VERIFIED', 'HR Verified'), ('RETURNED_TO_HOD', 'Returned to HOD'), ('PENDING_AUTHORIZATION', 'Pending Authorization'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('PDF_GENERATED', 'PDF Generated'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=32)),
                ('vote_code', models.CharField(blank=True, max_length=32)),
                ('sub_vote', models.CharField(blank=True, max_length=32)),
                ('check_number', models.CharField(blank=True, max_length=32)),
                ('personnel_file', models.CharField(blank=True, max_length=64)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('designation', models.CharField(blank=True, max_length=255)),
                ('station', models.CharField(blank=True, max_length=255)),
                ('division_department', models.CharField(blank=True, max_length=255)),
                ('phone_number', models.CharField(blank=True, max_length=32)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('contact_address', models.CharField(blank=True, max_length=255)),
                ('leave_number', models.CharField(blank=True, max_length=32)),
                ('travel_assistance', models.BooleanField(default=False)),
                ('start_date', models.DateField()),
                ('last_date', models.DateField()),
                ('total_working_days', models.PositiveIntegerField(blank=True, null=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leave_applications', to=settings.AUTH_USER_MODEL)),
                ('approval', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='leave.leaveapproval')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveDependant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('relationship', models.CharField(max_length=100)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependants', to='leave.leaveapplication')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveHRReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.BooleanField(blank=True, null=True)),
                ('leave_balance_confirmed', models.CharField(blank=True, max_length=100)),
                ('comments', models.TextField(blank=True)),
                ('signature_name', models.CharField(blank=True, max_length=255)),
                ('signature_designation', models.CharField(blank=True, max_length=255)),
                ('signature_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_hr_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='hr_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='leave.leavehrreview'),
        ),
        migrations.CreateModel(
            name='LeaveRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended', models.BooleanField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('signature_name', models.CharField(blank=True, max_length=255)),
                ('signature_designation', models.CharField(blank=True, max_length=255)),
                ('signature_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_recommendations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='recommendation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='leave.leaverecommendation'),
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='leave.leavetype'),
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(help_text='Balance period, e.g. calendar year "2026".', max_length=9)),
                ('opening_balance', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('entitlement', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('taken', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('pending', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('remaining', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='leave.leavetype')),
            ],
            options={
                'indexes': [models.Index(fields=['employee', 'leave_type', 'period'], name='leave_leave_employe_8210c0_idx')],
                'constraints': [models.UniqueConstraint(fields=('employee', 'leave_type', 'period'), name='uniq_balance_per_employee_type_period')],
            },
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['status'], name='leave_leave_status_bdd8c8_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['employee'], name='leave_leave_employe_a0ac9e_idx'),
        ),
        migrations.AddIndex(
            model_name='leaveapplication',
            index=models.Index(fields=['application_number'], name='leave_leave_applica_c06e8c_idx'),
        ),
    ]
