# Generated by Django 6.1.1 on 2026-09-09 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_years_of_service', models.PositiveIntegerField(blank=True, help_text='Inclusive lower bound on years of service. Leave blank for no lower bound.', null=True)),
                ('max_years_of_service', models.PositiveIntegerField(blank=True, help_text='Inclusive upper bound on years of service. Leave blank for no upper bound.', null=True)),
                ('annual_entitlement', models.DecimalField(decimal_places=2, help_text='Annual leave entitlement in days granted by this rule.', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower sort_order is matched first. Put more specific (tenure-banded) rules before flat ones.')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='leave.leavetype')),
            ],
            options={
                'verbose_name_plural': 'Leave policies',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
