# Generated by Django 6.1.1 on 2026-09-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0002_leavepolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavepolicy',
            name='designation',
            field=models.CharField(blank=True, help_text="Optional job grade/designation this rule applies to (matched case-insensitively against the employee's designation). Leave blank to apply to all designations.", max_length=255),
        ),
    ]
