# Generated by Django 5.2.17 on 2026-09-14 11:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0005_seed_person_types'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplication',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('PENDING_HOD_REVIEW', 'Pending HOD Review'), ('HOD_RECOMMENDED', 'HOD Recommended'), ('PENDING_CAG_REVIEW', 'Pending CAG Review'), ('CAG_RECOMMENDED', 'CAG Recommended'), ('RETURNED_TO_EMPLOYEE', 'Returned to Employee'), ('PENDING_HR_REVIEW', 'Pending HR Review'), ('HR_VERIFIED', 'HR Verified'), ('RETURNED_TO_HOD', 'Returned to HOD'), ('PENDING_AUTHORIZATION', 'Pending Authorization'), ('APPROVED', 'Approved'), ('DENIED', 'Denied'), ('PDF_GENERATED', 'PDF Generated'), ('COMPLETED', 'Completed'), ('ARCHIVED', 'Archived')], db_index=True, default='DRAFT', max_length=32),
        ),
        migrations.CreateModel(
            name='LeaveCAGReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommended', models.BooleanField(blank=True, null=True)),
                ('comments', models.TextField(blank=True)),
                ('signature_name', models.CharField(blank=True, max_length=255)),
                ('signature_designation', models.CharField(blank=True, max_length=255)),
                ('signature_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leave_cag_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='leaveapplication',
            name='cag_review',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='application', to='leave.leavecagreview'),
        ),
    ]
