# Generated by Django 5.2.17 on 2026-09-14 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0006_alter_leaveapplication_status_leavecagreview_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Holiday',
        ),
    ]
