# Generated by Django 5.2.17 on 2026-09-17 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0007_delete_holiday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='leavebalance',
            options={'ordering': ['-period', 'employee_id', 'leave_type_id']},
        ),
    ]
