# Generated by Django 5.2.17 on 2026-09-23 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave', '0009_add_aag_review_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPaymentSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_taxi_subtotal', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed TAXI subtotal per application (TZS). Blank = uncapped.', max_digits=12, null=True)),
                ('max_mizigo_subtotal', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum allowed MIZIGO subtotal per application (TZS). Blank = uncapped.', max_digits=12, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
